class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""
    def __init__(self):
        self.name = "Generic Event"

class TickEvent(Event):
    def __init__(self):
        self.name = "CPU Tick Event"

class QuitEvent(Event):
    def __init__(self):
        self.name = "Program Quit Event"

class MapLoadedEvent(Event):
    def __init__(self, map_screen):
        self.name = "Map Loaded Event"
        self.map_screen = map_screen

class CharacterPlacementEvent(Event):
    def __init__(self, character):
        self.name  = "Character Placement Event"
        self.character = character

class PlayerCharMoveRequest(Event):
    def __init__(self, direction):
        self.name = "Player Character Move Request"
	self.direction = direction

class PlayerCharStop(Event):
    def __init__(self, direction):
        self.name = "Player Character Stop"
	self.direction = direction

class CharacterMove(Event):
    def __init__(self, character):
        self.name = "Character Move"
        self.character = character

class ShiftPressed(Event):
    def __init__(self):
        self.name = "Shift Pressed"

class ShiftReleased(Event):
    def __init__(self):
        self.name = "Shift Released"
